### ISSUE TITLE
Music Volume (Main Menu)

### ISSUE THREAD

**Issue by HumzaShakoor** [seanmenzies/ShoniIsland#1]
**Describe the bug**
The Music stops playing once Master Volume is tampered with.

**To Reproduce**
1. Go to Options
2. Go to Sounds Tab
3. Click on Master Volume Slider 
4. Slide to 0
5. Slide to any point including max volume
6. All sounds continue except Music Volume

**Expected behavior**
Music is supposed to restart or continue

**Screenshots**
N/A

**Additional context**
N/A

**Comment by seanmenzies** [comment]
Fixed in today's patch
