### ISSUE TITLE
[Gameplay] Game Crashes After Totem Placement Near River

### ISSUE THREAD

**Issue by AizenGetsu93** [seanmenzies/ShoniIsland#102]
**Issue 1:** After destroying the ship and being prompted to place the totem in a highlighted green area, placing the totem in the allowed area near the river (with the destroyed ship) causes the game to crash.

**Issue 2:** Adjusting the frame rate per second (FPS) in the menu resolves the crash issue temporarily.

Severity:
Critical – Prevents progression in the tutorial and disrupts gameplay. The crash affects the core functionality of placing items.

Expected Results:

- The totem should be placeable in the highlighted green area without causing the game to crash.
- Players should be able to progress through the tutorial step seamlessly.

Actual Results:

- Placing the totem in the allowed area near the river consistently causes the game to crash.
- Manually adjusting the FPS setting in the menu resolves the issue temporarily.

Steps to Reproduce:

1. Destroy the ship as instructed in the tutorial.
2. Progress to the step prompting to place the totem in the highlighted green area.
3. Place the totem in the allowed location near the river and the destroyed ship.
4. Observe the game crash.
5. Adjust the FPS setting in the menu and retry the steps. Note that this temporarily prevents the crash.

Affected Version:

SHONI ISLAND BETA BUILD

Repro Frequency:
50% – Occurs when placing the totem near the river at the "Unlimited" FPS option within the Video Menu.

Environment:

- MSI Raider GE76
- 12th Gen Intel(R) Core(TM) i7-12700H 2.70 GHz
- NVIDIA GeForce RTX 3080 Laptop GPU
- Killer(R) Wi-Fi 6E AX1675i 160MHz Wireless Network Adapter (211NGW)
- Windows 11

**Comment by seanmenzies** [comment]
Based on the crash report, it looks like the crashed occurred when you tried to hit right click. Fixed in next patch.
