### ISSUE TITLE
Autosave file loading error

### ISSUE THREAD

**Issue by Dragnetic** [seanmenzies/ShoniIsland#105]
**Describe the bug**
Hi Sean when i am trying to load the game from autosave file it gets loading error.

**To Reproduce**
1. Go to Load Games
2. Click on "Autosave Menu"
3. Scroll down to any autosave files
4. Now click on any autosave files by pressing mouse right side button.

**Expected behavior**
The autosave file should load my last autosave game.

**Video**
https://drive.google.com/file/d/1MA8loL3XeBG0AqXuD65pVQL69g12B_gC/view?usp=sharing

**Comment by seanmenzies** [comment]
Autosave has been disabled during tutorial
