### ISSUE TITLE
Volume Resets (In Game)

### ISSUE THREAD

**Issue by HumzaShakoor** [seanmenzies/ShoniIsland#2]
**Describe the bug**
Sound Sliders are reset if slider is set to 0 once re-entering the sounds tab.

**To Reproduce**
1. Click Esc
2. Go to Options
3. Go to Sounds
4. Change any of the audio sliders to 0 and apply
5. Go back into Options
6. Go to Sounds
7. Sliders set to 0 are reset

**Expected behavior**
Keep the audio settings from previous change and available to increase audio from previous change.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by seanmenzies** [comment]
This is by design. Back = cancel. But I'll add a warning message in the next update.
