### ISSUE TITLE
When saving the game sometimes game menu buttons becomes unusable bug

### ISSUE THREAD

**Issue by Dragnetic** [seanmenzies/ShoniIsland#23]
**Describe the bug**
When you start playing the game and try to save the game sometimes when you saved the game successfully the game menu buttons becomes unusable. But the good thing is when the autosave happens the game menu becomes working again. P.S Autosave is a Hero.

**To Reproduce**
1. Click on New game
2. Keep playing the game normally and try to keep saving every few hours or so manually.
3. Sometimes not always when you saved the game successfully the menu becomes non - functional.
4. Then when the game performs the automatic autosave its automatically fixes the menu buttons.

**Expected behavior**
Game menu should always be functional.

**Screenshots**
![Screenshot (281)](https://github.com/seanmenzies/ShoniIsland/assets/83127443/ee35ae59-95df-45eb-8a04-bc291e4bbac1)

**Additional context**
Add any other context about the problem here. Note that on Windows, Steam automatically copies crash logs to the clipboard that can be pasted into the report.

**Comment by seanmenzies** [comment]
Hopefully caught this one
