### ISSUE TITLE
On saving game green color square box with stroke only lines is shown for a split second

### ISSUE THREAD

**Issue by Dragnetic** [seanmenzies/ShoniIsland#25]
**Describe the bug**
When we save a game every time once a successful saved message is shown the  green color square box with stroke only lines is shown for a split second

**To Reproduce**
1. Start playing the game
2. Press on "ESC Button"
3. A pop-up menu will come press on the "save game" button
4. Now either save the game on existing save file or click and give it a name click on right check mark to create a save game file
5. A pop-up message will show for both " Are you sure you want to overwrite the save game click on yes button
6. A message animation pop- up of " successfully saved the game will show up "
7. After it closes up a green button with stroke only lines rectangular shape with curve edges will show up for a split second

**Expected behavior**
On successfully creating a save file or successfully overwriting a save files the rectangular green with curve only stroke lines should not show up for split second.

**Screenshots**
Video link - https://drive.google.com/file/d/1ajIrd30_OglxOXJEe_RAj_lPAiJ6oWVv/view?usp=sharing

**Additional context**
Add any other context about the problem here. Note that on Windows, Steam automatically copies crash logs to the clipboard that can be pasted into the report.

**Comment by seanmenzies** [comment]
Fixed in today's patch
