### ISSUE TITLE
Can build buildings in river farming sides area

### ISSUE THREAD

**Issue by Dragnetic** [seanmenzies/ShoniIsland#26]
**Describe the bug**
I can build a building on where people farm fishes on the river side of the boat area.

**To Reproduce**
1. Launch the game
2. Click on " New Game "
3. Place a totem from the building menu
4. Select a any bulding from the build menu for eg :- Food storage
5. Now place it to a river side near a boat where people farm for fish.
6. See error

**Expected behavior**
Should not be able to build anything in fish areas.

**Screenshots**
![Building a anytype of build in near fish area](https://github.com/seanmenzies/ShoniIsland/assets/83127443/aac07896-8458-4aee-8458-af9e9b400c21)

**Additional context**
Add any other context about the problem here. Note that on Windows, Steam automatically copies crash logs to the clipboard that can be pasted into the report.

**Comment by seanmenzies** [comment]
Fixed
