### ISSUE TITLE
Loading of manual saves not working sometimes

### ISSUE THREAD

**Issue by Dragnetic** [seanmenzies/ShoniIsland#3]
**Describe the bug**
When on the main page we load the main save from the load menu it sometimes not works

**To Reproduce**
1. Go to main menu
2. Click on load menu
3. Scroll down to any saved files
4. Try to load it

**Expected behavior**
The game should load the main saved files

**Screenshots**
If applicable, add screenshots to help explain your [problem.](![Load files](https://github.com/seanmenzies/ShoniIsland/assets/83127443/be3609ab-a2a5-45fe-8cf3-4bf80c7c6237))

**Additional context**
Add any other context about the problem here. Note that on Windows, Steam automatically copies crash logs to the clipboard that can be pasted into the report.

**Comment by seanmenzies** [comment]
Fixed
