### ISSUE TITLE
from main menu autosaves not working also it can corrupt normal saves too

### ISSUE THREAD

**Issue by Dragnetic** [seanmenzies/ShoniIsland#4]
**Describe the bug**
When i go to main menu of the game and try to click on "Load Menu" and try to load autosaves it doesnt load but it then also corrupt the normal saves files to not load.

**To Reproduce**
1. Go to load menu from the game
2. Click on autosaved try to load it and click no
3. Scroll to normal save file and try to load it and click no

**Expected behavior**
The autosave file should load and it should also not corrupt the normal save file

**Screenshots**
![manual saves](https://github.com/seanmenzies/ShoniIsland/assets/83127443/dd7b8bda-e2f8-459e-a176-3491e43f32ab)

**Additional context**
Add any other context about the problem here. Note that on Windows, Steam automatically copies crash logs to the clipboard that can be pasted into the report.
![autosaved](https://github.com/seanmenzies/ShoniIsland/assets/83127443/6dedadad-9303-4576-903f-e4a532517e8e)

**Comment by seanmenzies** [comment]
Great, detailed report. Caught this bug, but music is still overlapping on load (autosaves only) so leaving this open until it's sorted.

**Comment by seanmenzies** [comment]
Music now fixed
