### ISSUE TITLE
Game crashing after 1 day at 11 pm daily

### ISSUE THREAD

**Issue by Dragnetic** [seanmenzies/ShoniIsland#5]
**Describe the bug**
Hi i was playing a new game and after 11pm the game is crashing on day 1

**To Reproduce**
1. Start the game as "New Game"
2. Play as you want
3. After 11 pm of day 1 the game crashes

**Expected behavior**
The game should not crash

**Screenshots**

**Additional context**
Add any other context about the problem here. Note that on Windows, Steam automatically copies crash logs to the clipboard that can be pasted into the report.

**Comment by seanmenzies** [comment]
Awaiting crash report when it happens next so I can inspect where the issue is coming from

**Comment by seanmenzies** [comment]
Fixed
