### ISSUE TITLE
Totem placement skip

### ISSUE THREAD

**Issue by And-i1** [seanmenzies/ShoniIsland#6]
**Describe the bug**
Saving and loading early in the game allows the player to unlock basic structures before placing the totem. Placing the totem after this will also duplicate the Basic Shelter option in the build menu.

**To Reproduce**
1. Create new game
2. Attempt to leave the game
3. Press save when the prompt appears
4. Load the save

**Screenshots**
![image](https://github.com/seanmenzies/ShoniIsland/assets/55852971/68e92b50-a55b-4275-b30f-64ae39f74d91)

**Additional context**
This also allows the player to have infinite building range as they are not limited by the totem.

**Comment by seanmenzies** [comment]
Good catch. Got it.
