### ISSUE TITLE
Construction workers don't work

### ISSUE THREAD

**Issue by And-i1** [seanmenzies/ShoniIsland#75]
**Describe the bug**
Trying to get the villagers to build in the tutorial does nothing.

**To Reproduce**
1. Go to 'New game'
2. Click on 'Yes'
3. Get to the point where you are asked to build a wood storage.

**Expected behavior**
To be able to build properly.

**Screenshots**
![image](https://github.com/user-attachments/assets/782ce23a-b0a9-467d-ad54-f4e2e99a1405)

**Additional context**
I'm using Manjaro Linux

**Comment by seanmenzies** [comment]
Fixed
