### ISSUE TITLE
Old main menu access

### ISSUE THREAD

**Issue by And-i1** [seanmenzies/ShoniIsland#8]
**Describe the bug**
Exiting to main menu can cause the old main menu to appear instead of the new one.

**To Reproduce**
1. Create a new game or load an old one
2. Attempt to leave the game
3. When the prompt appears, press the "Overwrite" option

**Expected behavior**
The normal menu to appear.

**Screenshots**

https://github.com/seanmenzies/ShoniIsland/assets/55852971/6d4b5b44-6464-4729-a5c3-2095beddc734

**Comment by seanmenzies** [comment]
Nice easy fix. More like this please!
