### ISSUE TITLE
When loading my saved files the game crashes

### ISSUE THREAD

**Issue by Dragnetic** [seanmenzies/ShoniIsland#93]
**Describe the bug**
 When i try to load my save game the game crashes.

**To Reproduce**
1. Go to Load Game
2. In save menu click on any save file you want to load the game.
3. The game crashes.

**Expected behavior**
The game should load properly

**Screenshots**

**Additional context**
Add any other context about the problem here. Note that on Windows, Steam automatically copies crash logs to the clipboard that can be pasted into the report.

**Comment by seanmenzies** [comment]
Should be fixed
