### ISSUE TITLE
Resources should be 0 before destroying the ship.

### ISSUE THREAD

**Issue by Dragnetic** [seanmenzies/ShoniIsland#96]
**Describe the bug**
When the game tutorial and it says destroy your ship. But your resources should be 0 before you destroy the ship but it shows 220 resources.

**To Reproduce**
1. Play the game tutorial
2. On tutorial when howard tells you to destroy the ship for resources but your resources before destroying the ship is 220 and after destroying it shows 220 no change.

**Expected behavior**
Before destroying your ship the resources should be showing you 0 and after destroying the ship the resources should be showing you 220.

**Video
![Screenshot (600)](https://github.com/user-attachments/assets/ca58e654-edf9-4433-8a90-55c267b90478)
**
https://drive.google.com/file/d/1nzShpzgs-B64W7Epss_MWkjdHDLf01uF/view?usp=drive_link

**Comment by seanmenzies** [comment]
Good find. Fixed.
