### ISSUE TITLE
Mouse UI and hand changes automatically

### ISSUE THREAD

**Issue by Dragnetic** [seanmenzies/ShoniIsland#97]
**Describe the bug**
When you play the game the mouse UI and hand sometimes changes automatically

**To Reproduce**
1. Play the game
2. See that your hand will automatically switches with UI and UI switches with hands.

**Expected behavior**
Until i press my mbb or my new custom key which i set instead of mbb it should not automatically change.

**video**
https://drive.google.com/file/d/1nzShpzgs-B64W7Epss_MWkjdHDLf01uF/view?usp=drive_link
https://drive.google.com/file/d/1RcX6kZU1M0Vc5SsL5VSuvmlFoWcVz_Xl/view?usp=drive_link

**Comment by seanmenzies** [comment]
Intended behavior. The hand will change if the player takes an action that can only be performed in one mode, and so switches to that mode. If the switching hinders your playthrough, let me know.

**Comment by Dragnetic** [comment]
Yes it causes problem i think my hand should not change to UI Click mode until i press mmb.
