### ISSUE TITLE
Wood Storage Is Not Getting Build In Tutorial.

### ISSUE THREAD

**Issue by Dragnetic** [seanmenzies/ShoniIsland#99]
**Describe the bug**
When playing the game tutorial and building the wood storage by dragging a player to it. The player don't start the construction of the wood storage.

**To Reproduce**
1. Play the tutorial
2. When you have to build a wood storage try to use your UI click to select inventory and drag a wood storage outside any place.
3. Then click and hold any player and drag it to your wood storage location.

**Expected behavior**
They should start building/construction of your wood storage.

**Video**
https://drive.google.com/file/d/1RcX6kZU1M0Vc5SsL5VSuvmlFoWcVz_Xl/view?usp=drive_link
https://drive.google.com/file/d/1nzShpzgs-B64W7Epss_MWkjdHDLf01uF/view?usp=drive_link

**Comment by seanmenzies** [comment]
Did you a) destroy the ship and b) select the "construction" speciality before dragging the villager over? This seems to be working as expected on my side.
